[package]
name = "scoped-futures"
version = "0.1.0"
edition = "2021"
authors = ["Trey Lowerison <trey@sidechainme.com>"]

[dependencies]
futures = { version = "0.3.24", features = ["alloc"], optional = true }
pin-utils = "0.1.0"

[features]
std = ["futures"]
