[package]
name = "scoped-futures"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sidechainme/scoped-futures"
homepage = "https://github.com/sidechainme/scoped-futures"
description = """
A utility crate for imposing upper bounds on Future lifetimes.
"""
categories = ["asynchronous"]
keywords = ["scope", "future", "futures", "hrtb", "liftime"]
include = ["**/*.rs", "Cargo.toml", "LICENSE-*"]

[dependencies]
futures = { version = "0.3.24", features = ["alloc"], optional = true }
pin-utils = "0.1.0"

[features]
std = ["futures"]
